#!/usr/bin/env bash
# Sync the generated CRDs into the Helm chart as templates.
#
# Helm installs files under a chart's crds/ directory on first install only and
# never touches them again on upgrade, silently. A templated CRD upgrades like
# any other resource; helm.sh/resource-policy: keep is what stops `helm
# uninstall` from taking the CRD — and every Automation with it — along.
#
# Run by `make manifests`. The output is committed; CI fails on drift.
set -euo pipefail

cd "$(dirname "$0")/.."

src="config/crd/bases"
out="charts/reactor/templates/crds.yaml"

shopt -s nullglob
crds=("$src"/*.yaml)
if [ ${#crds[@]} -eq 0 ]; then
	echo "sync-chart-crds: no CRDs in $src" >&2
	exit 1
fi

# The CRD becomes a Helm template, so Go-template delimiters anywhere in it —
# a description quoting {{ ... }}, say — would be rendered rather than shipped.
if grep -l '{{' "${crds[@]}"; then
	echo "sync-chart-crds: the CRDs above contain '{{', which Helm would render." >&2
	echo "Reword the offending description, or teach this script to escape it." >&2
	exit 1
fi

{
	echo "{{- /*"
	echo "Generated by 'make manifests' from config/crd/bases — do not edit."
	echo ""
	echo "Templated rather than shipped in crds/, because Helm never upgrades the"
	echo "latter. helm.sh/resource-policy: keep means an uninstall leaves the CRD"
	echo "and your Automations in place; delete it by hand if you mean to."
	echo ""
	echo "Defined rather than written out inline, because the chart needs these"
	echo "same bytes in two places: the release itself, and the ConfigMap the"
	echo "adoption hook patches from on the one upgrade where the CRD is not yet"
	echo "part of any release. See reactor.crdAdoption in _helpers.tpl."
	echo "*/}}"
	echo "{{- define \"reactor.crdManifest\" -}}"
	for crd in "${crds[@]}"; do
		echo "---"
		# The keep policy belongs to the chart, not to the API type, so it is
		# added here rather than through a +kubebuilder:metadata marker.
		awk '
			!injected && $0 == "  annotations:" {
				print
				print "    helm.sh/resource-policy: keep"
				injected = 1
				next
			}
			NR == 1 && $0 == "---" { next }
			{ print }
			END {
				if (!injected) {
					print "sync-chart-crds: no metadata.annotations block in " FILENAME >"/dev/stderr"
					exit 1
				}
			}
		' "$crd"
	done
	echo "{{- end -}}"
	echo "{{- if and .Values.crds.install (ne (include \"reactor.crdAdoption\" .) \"adopt\") }}"
	echo "{{- include \"reactor.crdManifest\" . }}"
	echo "{{- end }}"
} >"$out"

echo "sync-chart-crds: wrote $out from ${#crds[@]} CRD(s)"
