//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TargetRef)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(bool)
		**out = **in
	}
	if in.Cordoned != nil {
		in, out := &in.Cordoned, &out.Cordoned
		*out = new(bool)
		**out = **in
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(HTTPRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Notification != nil {
		in, out := &in.Notification, &out.Notification
		*out = new(Notification)
		**out = **in
	}
	if in.HomeAssistant != nil {
		in, out := &in.HomeAssistant, &out.HomeAssistant
		*out = new(HomeAssistantService)
		(*in).DeepCopyInto(*out)
	}
	if in.QBittorrent != nil {
		in, out := &in.QBittorrent, &out.QBittorrent
		*out = new(QBittorrent)
		**out = **in
	}
	if in.WLAN != nil {
		in, out := &in.WLAN, &out.WLAN
		*out = new(WLAN)
		**out = **in
	}
	if in.PoE != nil {
		in, out := &in.PoE, &out.PoE
		*out = new(PoEPort)
		**out = **in
	}
	if in.Outlet != nil {
		in, out := &in.Outlet, &out.Outlet
		*out = new(Outlet)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Automation) DeepCopyInto(out *Automation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Automation.
func (in *Automation) DeepCopy() *Automation {
	if in == nil {
		return nil
	}
	out := new(Automation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Automation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationList) DeepCopyInto(out *AutomationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Automation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationList.
func (in *AutomationList) DeepCopy() *AutomationList {
	if in == nil {
		return nil
	}
	out := new(AutomationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutomationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationSpec) DeepCopyInto(out *AutomationSpec) {
	*out = *in
	if in.When != nil {
		in, out := &in.When, &out.When
		*out = new(StateTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnExit != nil {
		in, out := &in.OnExit, &out.OnExit
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationSpec.
func (in *AutomationSpec) DeepCopy() *AutomationSpec {
	if in == nil {
		return nil
	}
	out := new(AutomationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationStatus) DeepCopyInto(out *AutomationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Matching != nil {
		in, out := &in.Matching, &out.Matching
		*out = new(bool)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransition != nil {
		in, out := &in.LastTransition, &out.LastTransition
		*out = new(StateTransition)
		(*in).DeepCopyInto(*out)
	}
	if in.LastExecution != nil {
		in, out := &in.LastExecution, &out.LastExecution
		*out = new(ExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.EdgeActions != nil {
		in, out := &in.EdgeActions, &out.EdgeActions
		*out = make([]EdgeExecutionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationStatus.
func (in *AutomationStatus) DeepCopy() *AutomationStatus {
	if in == nil {
		return nil
	}
	out := new(AutomationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeExecutionStatus) DeepCopyInto(out *EdgeExecutionStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeExecutionStatus.
func (in *EdgeExecutionStatus) DeepCopy() *EdgeExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStatus) DeepCopyInto(out *ExecutionStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStatus.
func (in *ExecutionStatus) DeepCopy() *ExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHeader) DeepCopyInto(out *HTTPHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHeader.
func (in *HTTPHeader) DeepCopy() *HTTPHeader {
	if in == nil {
		return nil
	}
	out := new(HTTPHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRequest) DeepCopyInto(out *HTTPRequest) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]HTTPHeader, len(*in))
		copy(*out, *in)
	}
	if in.Idempotent != nil {
		in, out := &in.Idempotent, &out.Idempotent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRequest.
func (in *HTTPRequest) DeepCopy() *HTTPRequest {
	if in == nil {
		return nil
	}
	out := new(HTTPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantService) DeepCopyInto(out *HomeAssistantService) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Idempotent != nil {
		in, out := &in.Idempotent, &out.Idempotent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantService.
func (in *HomeAssistantService) DeepCopy() *HomeAssistantService {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notification) DeepCopyInto(out *Notification) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notification.
func (in *Notification) DeepCopy() *Notification {
	if in == nil {
		return nil
	}
	out := new(Notification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Outlet) DeepCopyInto(out *Outlet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Outlet.
func (in *Outlet) DeepCopy() *Outlet {
	if in == nil {
		return nil
	}
	out := new(Outlet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoEPort) DeepCopyInto(out *PoEPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoEPort.
func (in *PoEPort) DeepCopy() *PoEPort {
	if in == nil {
		return nil
	}
	out := new(PoEPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QBittorrent) DeepCopyInto(out *QBittorrent) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QBittorrent.
func (in *QBittorrent) DeepCopy() *QBittorrent {
	if in == nil {
		return nil
	}
	out := new(QBittorrent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReversalIntent) DeepCopyInto(out *ReversalIntent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReversalIntent.
func (in *ReversalIntent) DeepCopy() *ReversalIntent {
	if in == nil {
		return nil
	}
	out := new(ReversalIntent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateTransition) DeepCopyInto(out *StateTransition) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateTransition.
func (in *StateTransition) DeepCopy() *StateTransition {
	if in == nil {
		return nil
	}
	out := new(StateTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateTrigger) DeepCopyInto(out *StateTrigger) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateTrigger.
func (in *StateTrigger) DeepCopy() *StateTrigger {
	if in == nil {
		return nil
	}
	out := new(StateTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPreview) DeepCopyInto(out *TargetPreview) {
	*out = *in
	if in.Desired != nil {
		in, out := &in.Desired, &out.Desired
		*out = new(int32)
		**out = **in
	}
	if in.Effective != nil {
		in, out := &in.Effective, &out.Effective
		*out = new(int32)
		**out = **in
	}
	if in.DeferredBy != nil {
		in, out := &in.DeferredBy, &out.DeferredBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WouldDefer != nil {
		in, out := &in.WouldDefer, &out.WouldDefer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPreview.
func (in *TargetPreview) DeepCopy() *TargetPreview {
	if in == nil {
		return nil
	}
	out := new(TargetPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
	if in.Desired != nil {
		in, out := &in.Desired, &out.Desired
		*out = new(int32)
		**out = **in
	}
	if in.Effective != nil {
		in, out := &in.Effective, &out.Effective
		*out = new(int32)
		**out = **in
	}
	if in.DeferredBy != nil {
		in, out := &in.DeferredBy, &out.DeferredBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preview != nil {
		in, out := &in.Preview, &out.Preview
		*out = new(TargetPreview)
		(*in).DeepCopyInto(*out)
	}
	if in.ReversalDisagreement != nil {
		in, out := &in.ReversalDisagreement, &out.ReversalDisagreement
		*out = make([]ReversalIntent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WLAN) DeepCopyInto(out *WLAN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WLAN.
func (in *WLAN) DeepCopy() *WLAN {
	if in == nil {
		return nil
	}
	out := new(WLAN)
	in.DeepCopyInto(out)
	return out
}
